FROM python:3.5-alpine
COPY . /code
WORKDIR /code
RUN python setup.py install
RUN pip install gunicorn
ARG PORT="8912"
ARG WORKERS="4"
ARG TIMEOUT="30"
ARG VERBOSITY="WARN"
ARG SECRET_KEY="provideThisAtBuildTime"
ARG STORAGE_BACKEND
ARG MONGO_HOST
ARG MONGO_PORT
ARG MONGO_DB
ARG SWIFT_AUTH_URL
ARG SWIFT_AUTH_VERSION
ARG SWIFT_USER
ARG SWIFT_KEY
ARG SWIFT_TENANT_NAME
ARG SWIFT_CONTAINER_NAME
ARG SWIFT_SECRET_KEY
ENV \
    ARCHSTOR_STORAGE_BACKEND=${STORAGE_BACKEND} \
    ARCHSTOR_MONGO_HOST=${MONGO_HOST} \
    ARCHSTOR_MONGO_PORT=${MONGO_PORT} \
    ARCHSTOR_MONGO_DB=${MONGO_DB} \
    ARCHSTOR_SWIFT_AUTH_URL=${SWIFT_AUTH_URL} \
    ARCHSTOR_SWIFT_AUTH_VERSION=${SWIFT_AUTH_VERSION} \
    ARCHSTOR_SWIFT_USER=${SWIFT_USER} \
    ARCHSTOR_SWIFT_KEY=${SWIFT_KEY} \
    ARCHSTOR_SWIFT_TENANT_NAME=${SWIFT_TENANT_NAME} \
    ARCHSTOR_SWIFT_CONTAINER_NAME=${SWIFT_CONTAINER_NAME} \
    ARCHSTOR_SWIFT_SECRET_KEY=${SECRET_KEY} \
    WORKERS=${WORKERS} \
    PORT=${PORT} \
    TIMEOUT=${TIMEOUT} \
    ARCHSTOR_VERBOSITY=${VERBOSITY}
CMD gunicorn archstor:app -w ${WORKERS} -t ${TIMEOUT} -b 0.0.0.0:${PORT}
